### ISSUE TITLE
Add Feature: Ignore URL Patterns

### ISSUE THREAD

**Issue by MLJBrackett** [jongwon-jang/detectURL#7]
Users want to be able to run our link checker tools and be able to include an extra argument, a file of URL patterns to be ignored. 

If the file has these lines in it, it should ignore senecacollege urls & learn.senecacollege urls
```
# Ignore All Seneca College URLs
https://senecacollege.ca
# Ignore all Learn@Seneca URLs
https://learn.senecacollege.ca/
````
I would like to add this feature into your code base based on the lab 4 requirements

**Comment by jongwon-jang** [comment]
Please go ahead and add the feature!
Thanks :-)

**Comment by MLJBrackett** [comment]
HI @jongwon-jang I have completed the feature, it is on my branch issue-7 on my git repository. Please add my fork as a remote, fetch, and test my branch as per step 5 requirements of the lab.

You can find it here: https://github.com/MLJBrackett/detectURL/tree/issue-7
